version: "3"
services:
  api:
    build:
      context: .
    container_name: api
    image: api
    restart: always
    volumes:
      - ./iris_processed.csv:/app/iris1.csv
    ports:
      - "8000:8000"
    command: "python -m uvicorn main:app --host 0.0.0.0"
#docker compose up -d
#docker-compose up -d

#docker compose down
#docker image rm api
